export const REQUEST_HEALTH_DATA_TO_SPRING = 'REQUEST_HEALTH_DATA_TO_SPRING'
// export const REQUEST_HEALTH_AMOUNT_TO_SPRING = 'REQUEST_HEALTH_AMOUNT_TO_SPRING'
// export const REQUEST_HEALTH_DATE_TO_SPRING = 'REQUEST_HEALTH_DATE_TO_SPRING'
