version: "3.7"
services:
  app:
    image: ghcr.io/reberel/kdt-ai-1-lecturenotes:latest
    container_name: docker-fastapi-deploy-server
    ports:
      - 8000:8000
    networks:
      - app

networks:
  app:
    driver: bridge