export const REQUEST_BOARD_LIST_TO_SPRING = 'REQUEST_BOARD_LIST_TO_SPRING'
//REQUEST_BOARD_LIST_TO_SPRING를 'REQUEST_BOARD_LIST_TO_SPRING'로 하겠다.
export const REQUEST_BOARD_TO_SPRING = 'REQUEST_BOARD_TO_SPRING'