version: "3.7"
services:
  nginx:
    image: "nginx:latest"
    container_name: micro-frontend-deploy-nginx
    restart: unless-stopped
    volumes:
      - /home/ec2-user/mfe/conf:/efc/nginx/conf.d
      - /home/ec2-user/mfe/vue:/usr/share/nginx/html/vue
    ports:
      - "80:80"
    networks:
      - app

networks:
  app:
    driver: bridge