version: "3.7"
services:
  frontend:
    image: ghcr.io/yeoulcho/KDT-AI-1-LectureNotes:latest
    container_name: docker-fastapi-deploy-server
    ports:
      - 8000:8000
    networks:
      - app

networks:
  app:
    driver: bridge

